### ISSUE TITLE
Windows Universal App (8.1) failed to call subscribeToPushService()

### ISSUE THREAD

**Issue by vwong53** [Pushwoosh/pushwoosh-windows-8-sdk#4]
My application get hanged when it reaches this function subscribeToPushService(). When i disable it, the application runs smoothly. But i cannot retrieve the pushToken value. 

I did it include the PushSDK reference and also adding the c# PushSDK project into my application.
The platform i'm working on is windows 8.1 universal app. 

Please kindly advice how should i do to get the push notification work on this window platform. 
Thanks

**Comment by shaders** [comment]
Please try again with the new build. We have identified potential deadlock, it should be fixed in the newest build. Please let me know the results.
