### ISSUE TITLE
Detect if the app was launched/opened from a push notification

### ISSUE THREAD

**Issue by luissilvaos** [Pushwoosh/pushwoosh-windows-8-sdk#7]
Hi guys,

Is there any way to detect if the application was launched/opened from a push notification?
I have a use case where I need access to the custom data of a push notification, but when the user  touch the notification the application restarts...

Cheers

**Comment by shaders** [comment]
Unfortunately that's the way how Windows handles push notification (It's confusing me as well).

Take a look here:
https://github.com/Pushwoosh/pushwoosh-native-samples/blob/master/Win8/PushWooshSample/App.xaml.cs

    protected override void OnLaunched(LaunchActivatedEventArgs args)
    {
            NotificationService.HandleStartPush(args.Arguments);

If this is not null - it will be start push data.
